objects/Vosf_Question_Column__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsEditable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsEditable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Total_Validation_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Total Validation Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Label__c</fullName>
        <label>Label</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <label>Question</label>
        <referenceTo>Vosf_Question__c</referenceTo>
        <relationshipLabel>Question Columns</relationshipLabel>
        <relationshipName>Question_Columns</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Required_Total__c</fullName>
        <label>Required Total</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sequence_Number__c</fullName>
        <label>Sequence Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Text</fullName>
                </value>
                <value>
                    <fullName>Number</fullName>
                </value>
                <value>
                    <fullName>Formula</fullName>
                </value>
                <value>
                    <fullName>Output</fullName>
                </value>
                <value>
                    <fullName>Question</fullName>
                </value>
                <value>
                    <fullName>Combobox</fullName>
                </value>
                <value>
                    <fullName>Unselect Row</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Question Column</label>
    <nameField>
        <label>Question Column Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Question Columns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Vosf_QuestionColumnDAO.cls
public with sharing class Vosf_QuestionColumnDAO {
	public static List<Vosf_Question_Column__c> getByQuestions(List<Id> questionIds){
        return [SELECT Id,Description__c, IsEditable__c, Label__c,
                Is_Total_Validation_Required__c, Question__c, 
                Required_Total__c, Sequence_Number__c, Type__c 
                FROM Vosf_Question_Column__c
                WHERE Question__c in : questionIds];
    }
    
    public static List<Vosf_Question_Column__c> insertColumns(List<Vosf_Question_Column__c> columnList){
        insert columnList;
        return columnList;
    }
}