objects/Vosf_Survey_Invitation__c.object
<CustomObject>
    <fields>
        <fullName>Participant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Participant</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Survey_Invitations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Survey</label>
        <referenceTo>Vosf_Survey__c</referenceTo>
        <relationshipLabel>Survey Invitations</relationshipLabel>
        <relationshipName>Survey_Invitations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Survey Invitation</label>
    <nameField>
        <displayFormat>SI-{YY}{MM}{00000}</displayFormat>
        <label>Survey Invitation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Invitations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/Vosf_UserDAO.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 06-01-2023
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
//AND ID NOT IN (SELECT Participant__c FROM Vosf_Survey_Invitation__c WHERE Survey__c =:surveyId)
public class Vosf_UserDAO {
    public static final String strQuery1='SELECT Id,Email,';
    public static final String strQuery2=' IsActive FROM User WHERE IsActive = TRUE';
/**
 * @param strfield fields to fetch dyanamically 
 * @return  `List<User>`
 */
    public static List<User> getActiveUsers(String strfield){
        return Database.query(strQuery1+strfield+strQuery2);
    }
/**
 * @description return participant of survey
 * @param surveyId 
 * @return  `Map<Id, Vosf_Survey_Invitation__c>`
 */
    public static Map<Id, Vosf_Survey_Invitation__c>  getInvitedUsers(Id surveyId){
        Map<Id, Vosf_Survey_Invitation__c> invitesmap = new Map<Id, Vosf_Survey_Invitation__c>();
        List<Vosf_Survey_Invitation__c> listInvites=[ SELECT Participant__c,Status__c  FROM Vosf_Survey_Invitation__c  WHERE Survey__c=:surveyId];
        for (Vosf_Survey_Invitation__c invobj : listInvites) {
            invitesmap.put(invobj.Participant__c,invobj);
        }
        return invitesmap;
    }
/**
 * @description return user for provided roles
 * @param surveyId 
 * @param roles 
 * @return  `List<User>`
 */
    public static List<User> getActiveUsersByRole(Id surveyId,List<String> roles){
        return [SELECT Id,Name,UserRole.Name,IsActive FROM User WHERE IsActive = TRUE AND ID NOT IN (SELECT Participant__c FROM Vosf_Survey_Invitation__c WHERE Survey__c =:surveyId) AND UserRole.Name IN:roles ];
    }
}