objects/Vosf_Question__c.object
<CustomObject>
    <fields>
        <fullName>Controlling_Question_Column__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Controlling Question Column</label>
        <referenceTo>Vosf_Question_Column__c</referenceTo>
        <relationshipLabel>Questions</relationshipLabel>
        <relationshipName>Questions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Controlling_Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Controlling Question</label>
        <referenceTo>Vosf_Question__c</referenceTo>
        <relationshipName>Questions1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>100000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>IsRequired__c</fullName>
        <defaultValue>true</defaultValue>
        <label>isRequired</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Total_Validation_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Total Validation Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Module__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Module</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Vosf_Module__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Module</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Vosf_Module__c</referenceTo>
        <relationshipLabel>Questions (Module)</relationshipLabel>
        <relationshipName>Questions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Parent_Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Question</label>
        <referenceTo>Vosf_Question__c</referenceTo>
        <relationshipName>Questions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Question_Label__c</fullName>
        <label>Question Label</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Question_Type__c</fullName>
        <label>Question Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Combobox</fullName>
                </value>
                <value>
                    <fullName>Radio</fullName>
                </value>
                <value>
                    <fullName>Multiselect</fullName>
                </value>
                <value>
                    <fullName>Number</fullName>
                </value>
                <value>
                    <fullName>Text</fullName>
                </value>
                <value>
                    <fullName>Table</fullName>
                </value>
                <value>
                    <fullName>TextArea</fullName>
                </value>
                <value>
                    <fullName>Checkbox</fullName>
                </value>
                <value>
                    <fullName>Slider</fullName>
                </value>
                <value>
                    <fullName>Rating</fullName>
                </value>
                <value>
                    <fullName>Comment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sequence_Number__c</fullName>
        <label>Sequence Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/Vosf_QuestionDAO.cls
public with sharing class Vosf_QuestionDAO {
    public static Vosf_Question__c getById(String questionId){
        List<Vosf_Question__c> questionList = 
            [SELECT Id, Controlling_Question__c, Controlling_Question_Column__c, Description__c,
                Is_Total_Validation_Required__c, isRequired__c, Module__c,
                Sequence_Number__c, Parent_Question__c, Question_Label__c, Name,
                Question_Type__c
             FROM Vosf_Question__c 
             WHERE Id = : questionId
            ];
        
        if(questionList != null && !questionList.isEmpty()){
            return questionList[0];
        }
        
        return null;
    }
    
    public static List<Vosf_Question__c> insertQuestions(List<Vosf_Question__c> questionList){
        insert questionList;
        return questionList;
    }
    
    public static List<Vosf_Question__c> getByParent(String questionId){
        return [
            SELECT Id, Controlling_Question__c, Controlling_Question_Column__c, Description__c,
                Is_Total_Validation_Required__c, isRequired__c, Module__c,
                Sequence_Number__c, Parent_Question__c, Question_Label__c, Name,
                Question_Type__c
            FROM Vosf_Question__c 
            WHERE Parent_Question__c = : questionId
        ];
    }
    
    public static List<Vosf_Question__c> getByGrandParent(String questionId){
        return [
            SELECT Id, Controlling_Question__c, Controlling_Question_Column__c, Description__c,
                Is_Total_Validation_Required__c, isRequired__c, Module__c,
                Sequence_Number__c, Parent_Question__c, Question_Label__c, Name,
                Question_Type__c
            FROM Vosf_Question__c 
            WHERE Parent_Question__r.Parent_Question__c = : questionId
        ];
    }    
    
}