objects/Vosf_Survey_Invitation__c.object
<CustomObject>
    <fields>
        <fullName>Due_Date__c</fullName>
        <defaultValue>TODAY() + $Setup.Vosf_Survey_Setting__c.Due_Date_Period__c</defaultValue>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Participant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Participant</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Survey_Invitations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Send_Reminder__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Send Reminder</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Survey_Link__c</fullName>
        <label>Survey Link</label>
        <type>Url</type>
    </fields>
    <label>Survey Invitation</label>
    <nameField>
        <displayFormat>SI-{YY}{MM}{00000}</displayFormat>
        <label>Survey Invitation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Invitations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Vosf_Survey_Setting__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>First_Reminder_Period__c</fullName>
        <label>First Reminder Period</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Second_Reminder_Period__c</fullName>
        <label>Second Reminder Period</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Send_Reminder_Email__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Send Reminder Email</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Survey_Org_Base_URL__c</fullName>
        <label>Survey Org Base URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Third_Reminder_Period__c</fullName>
        <label>Third Reminder Period</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Survey Setting</label>
</CustomObject>

classes/Vosf_SurveyReminderBatch.cls
public class Vosf_SurveyReminderBatch implements Schedulable,Database.Batchable<sObject>{
   VOSF_Survey_Setting__c vosfSetting= [SELECT Id,Survey_Org_Base_URL__c,First_Reminder_Period__c,Second_Reminder_Period__c,Third_Reminder_Period__c,Send_Reminder_Email__c  FROM Vosf_Survey_Setting__c LIMIT 1]; 
    public Database.QueryLocator start(Database.BatchableContext bc){
        Date firstReminder=Date.Today().addDays(- Integer.valueOf(vosfSetting.First_Reminder_Period__c));
        Date secondReminder=Date.Today().addDays(- Integer.valueOf(vosfSetting.Second_Reminder_Period__c));
        Date thirdReminder=Date.Today().addDays(- Integer.valueOf(vosfSetting.Third_Reminder_Period__c));
        String[] status = new String[] {'In Progress','Not Started'}; 

        String query = 'SELECT Id, Participant__r.Email, Survey_Link__c, Participant__r.FirstName, Send_Reminder__c, Due_Date__c  FROM Vosf_Survey_Invitation__c WHERE Send_Reminder__c =true AND Status__c IN :status AND Participant__r.IsActive= true AND (Due_Date__c =TODAY OR Due_Date__c=:firstReminder OR Due_Date__c=:secondReminder OR Due_Date__c=:thirdReminder)';
        return Database.getQueryLocator(query);
    }
    public void execute(Database.BatchableContext bc, List<Vosf_Survey_Invitation__c> scope){
      sendReminderEmail(scope);
       
    }
    public void finish(Database.BatchableContext bc){
    }
    public void execute(SchedulableContext scon) {
        if (vosfSetting.Send_Reminder_Email__c) {
            Database.executeBatch(new Vosf_SurveyReminderBatch());  
        }
       
    }

    public  void  sendReminderEmail(List<Vosf_Survey_Invitation__c> surveyInviteList){
      List<Messaging.SingleEmailMessage> emails = new List<Messaging.SingleEmailMessage>();
      for(Vosf_Survey_Invitation__c vsi:surveyInviteList){
    Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
      String[] toAddresses = new String[] {vsi.Participant__r.Email}; 
      mail.setToAddresses(toAddresses);
      mail.setHtmlBody(createBody(vsi.Participant__r.FirstName,vsi.Survey_Link__c));
      mail.setSubject('Gentle reminder to complete survey');
          emails.add(mail);
      }
      Messaging.sendEmail(emails);
  }
  public  string createBody(string userName,string link){
  return '<p><b> Hi '+userName+',</b></p> <p>This is gentle reminder to complete pending survey. Please find link below:</p><p><b> Survey Link:</b> '+link+'</p>';
 
}
}