objects/Vosf_Module__c.object
<CustomObject>
    <fields>
        <fullName>Sequence_Number__c</fullName>
        <label>Sequence Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Module</label>
    <nameField>
        <label>Module Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Modules</pluralLabel>
    <recordTypes>
        <fullName>Module</fullName>
        <active>true</active>
        <label>Module</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Vosf_Question__c.object
<CustomObject>
    <fields>
        <fullName>Question_Label__c</fullName>
        <label>Question Label</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Question_Type__c</fullName>
        <label>Question Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Combobox</fullName>
                </value>
                <value>
                    <fullName>Radio</fullName>
                </value>
                <value>
                    <fullName>Multiselect</fullName>
                </value>
                <value>
                    <fullName>Number</fullName>
                </value>
                <value>
                    <fullName>Text</fullName>
                </value>
                <value>
                    <fullName>Table</fullName>
                </value>
                <value>
                    <fullName>TextArea</fullName>
                </value>
                <value>
                    <fullName>Checkbox</fullName>
                </value>
                <value>
                    <fullName>Slider</fullName>
                </value>
                <value>
                    <fullName>Rating</fullName>
                </value>
                <value>
                    <fullName>Comment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sequence_Number__c</fullName>
        <label>Sequence Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Vosf_Question_Choice__c.object
<CustomObject>
    <fields>
        <fullName>Question_Choice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Question Choice</label>
        <referenceTo>Vosf_Question_Choice__c</referenceTo>
        <relationshipLabel>Question Choices</relationshipLabel>
        <relationshipName>Question_Choices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <label>Question</label>
        <referenceTo>Vosf_Question__c</referenceTo>
        <relationshipLabel>Question Choices</relationshipLabel>
        <relationshipName>Question_Choices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Sequence_Number__c</fullName>
        <formula>Question_Column__r.Sequence_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sequence Number</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Input</fullName>
                </value>
                <value>
                    <fullName>Formula SUM</fullName>
                </value>
                <value>
                    <fullName>Formula Value</fullName>
                </value>
                <value>
                    <fullName>Formula Percentage</fullName>
                </value>
                <value>
                    <fullName>Output</fullName>
                </value>
                <value>
                    <fullName>Number</fullName>
                </value>
                <value>
                    <fullName>Text</fullName>
                </value>
                <value>
                    <fullName>Radio</fullName>
                </value>
                <value>
                    <fullName>Checkbox</fullName>
                </value>
                <value>
                    <fullName>TextArea</fullName>
                </value>
                <value>
                    <fullName>Slider</fullName>
                </value>
                <value>
                    <fullName>Combobox</fullName>
                </value>
                <value>
                    <fullName>Multiselect</fullName>
                </value>
                <value>
                    <fullName>Formula 1</fullName>
                </value>
                <value>
                    <fullName>Formula 2</fullName>
                </value>
                <value>
                    <fullName>Formula 3</fullName>
                </value>
                <value>
                    <fullName>Formula 4</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Question Choice</label>
    <nameField>
        <displayFormat>QC-{YY}{MM}{00000}</displayFormat>
        <label>Question Choice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Choices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Vosf_Question_Response__c.object
<CustomObject>
    <fields>
        <fullName>Question_Choice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Question Choice</label>
        <referenceTo>Vosf_Question_Choice__c</referenceTo>
        <relationshipLabel>Question Responses</relationshipLabel>
        <relationshipName>Question_Responses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Question</label>
        <referenceTo>Vosf_Question__c</referenceTo>
        <relationshipLabel>Question Responses</relationshipLabel>
        <relationshipName>Question_Responses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Response__c</fullName>
        <label>Response</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Question Response</label>
    <nameField>
        <label>Question Response Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Question Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Vosf_Question_Visibility_Criteria__c.object
<CustomObject>
    <fields>
        <fullName>Operator__c</fullName>
        <label>Operator</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>=</fullName>
                </value>
                <value>
                    <fullName>&gt;</fullName>
                </value>
                <value>
                    <fullName>&lt;</fullName>
                </value>
                <value>
                    <fullName>&gt;=</fullName>
                </value>
                <value>
                    <fullName>&lt;=</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Question_Choice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Question Choice</label>
        <referenceTo>Vosf_Question_Choice__c</referenceTo>
        <relationshipLabel>Question Visibility Criteria</relationshipLabel>
        <relationshipName>Question_Visibility_Criteria</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Question_Visibility_Rule__c</fullName>
        <label>Question Visibility Rule</label>
        <referenceTo>Vosf_Question_Visibility_Rule__c</referenceTo>
        <relationshipLabel>Question Visibility Criteria</relationshipLabel>
        <relationshipName>Question_Visibility_Criteria</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Question Visibility Criteria</label>
    <nameField>
        <label>Question Visibility Criteria Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Question Visibility Criteria</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Vosf_Question_Visibility_Rule__c.object
<CustomObject>
    <fields>
        <fullName>Dependent_Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Dependent Question</label>
        <referenceTo>Vosf_Question__c</referenceTo>
        <relationshipLabel>Question Visibility Rules (Dependant Question)</relationshipLabel>
        <relationshipName>Question_Visibility_Rules1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <label>Question</label>
        <referenceTo>Vosf_Question__c</referenceTo>
        <relationshipLabel>Question Visibility Rules</relationshipLabel>
        <relationshipName>Question_Visibility_Rules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Question Visibility Rule</label>
    <nameField>
        <label>Question Visibility Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Question Visibility Rules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Vosf_Related_Question__c.object
<CustomObject>
    <fields>
        <fullName>Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Question</label>
        <referenceTo>Vosf_Question__c</referenceTo>
        <relationshipLabel>Related Questions</relationshipLabel>
        <relationshipName>Related_Questions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Related Question</label>
    <nameField>
        <displayFormat>RQ-{0000}</displayFormat>
        <label>Vosf_Related Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Related Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Vosf_Survey_Invitation__c.object
<CustomObject>
    <fields>
        <fullName>Survey__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Survey</label>
        <referenceTo>Vosf_Survey__c</referenceTo>
        <relationshipLabel>Survey Invitations</relationshipLabel>
        <relationshipName>Survey_Invitations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Survey Invitation</label>
    <nameField>
        <displayFormat>SI-{YY}{MM}{00000}</displayFormat>
        <label>Survey Invitation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Invitations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Vosf_Survey_Question__c.object
<CustomObject>
    <fields>
        <fullName>Question__c</fullName>
        <label>Question</label>
        <referenceTo>Vosf_Question__c</referenceTo>
        <relationshipName>Vosf_Survey_Questions</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <label>Survey</label>
        <referenceTo>Vosf_Survey__c</referenceTo>
        <relationshipName>Vosf_Survey_Questions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Survey Question</label>
    <nameField>
        <displayFormat>SQ-{0000}</displayFormat>
        <label>Vosf Validation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Vosf_Survey_Setting__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>First_Reminder_Period__c</fullName>
        <label>First Reminder Period</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Second_Reminder_Period__c</fullName>
        <label>Second Reminder Period</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Send_Reminder_Email__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Send Reminder Email</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Survey_Org_Base_URL__c</fullName>
        <label>Survey Org Base URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Third_Reminder_Period__c</fullName>
        <label>Third Reminder Period</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Survey Setting</label>
</CustomObject>

classes/Vosf_TestDataFactory.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 05-10-2023
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/

public with sharing class Vosf_TestDataFactory {
   
    public static List<Vosf_Question_Visibility_Rule__c> insertQuestionVisibilityRule(Boolean isInsert,List<Vosf_Question_Visibility_Rule__c> visibilityRuleList) {
        if (isInsert) {
            insert visibilityRuleList;
        }
        return visibilityRuleList;
        
    }
    public static List<Vosf_Question_Visibility_Criteria__c> insertQuestionVisibilityCriteria(Boolean isInsert,List<Vosf_Question_Visibility_Criteria__c> visibilityCriteria) {
        if (isInsert) {
            insert visibilityCriteria;
        }
        return visibilityCriteria;
        
    }
    public static List<Vosf_Question_Choice__c> insertQuestionChoices(Boolean isInsert,List<Vosf_Question_Choice__c> questionChoices) {
        if (isInsert) {
            insert questionChoices;
        }
        return questionChoices;
        
    }
    public static List<Vosf_Question_Response__c> insertQuestionResponses(Boolean isInsert,List<Vosf_Question_Response__c> questionResponses) {
        if (isInsert) {
            insert questionResponses;
        }
        return questionResponses;
        
    }
    
    public static Vosf_Module__c createModule(Boolean isInsert,String name,String recordTypeId) {
        Vosf_Module__c module = new Vosf_Module__c(Name = name,RecordTypeId = recordTypeId);
        if (isInsert) {
            insert module;
        }
        return module;    
    }
    
    public static Vosf_Survey_Setting__c createSurveySetting(Boolean isInsert,Boolean sendReminderEmail) {
        Vosf_Survey_Setting__c  surveySetting = new Vosf_Survey_Setting__c (Survey_Org_Base_URL__c = 'https://test-1f8-dev-ed.develop.lightning.force.com/lightning/n/VOSF_Survey?c__SurveyInvitationId=',
                                                                           First_Reminder_Period__c = 0,
                                                                           Second_Reminder_Period__c = 2,
                                                                           Third_Reminder_Period__c = 4,
                                                                           Send_Reminder_Email__c = sendReminderEmail);
        if (isInsert) {
            insert surveySetting;
        }
        return surveySetting;    
    }
    public static Vosf_Question__c createQuestion(Boolean isInsert,String type,String questionText) {
        Vosf_Question__c qns=new Vosf_Question__c(Question_Type__c=type,Sequence_Number__c=1,Question_Label__c=questionText, Name=questionText);
        if (isInsert) {
            insert qns;
        }
        return qns;
        
    }
    public static Vosf_Question_Visibility_Rule__c createQuestionVisibilityRule(Boolean isInsert,Id questionid,Id depedantQuestionId) {
        Vosf_Question_Visibility_Rule__c qvr =new Vosf_Question_Visibility_Rule__c(Question__c=questionid,Dependent_Question__c=depedantQuestionId);
        if (isInsert) {
            insert qvr;
        }
        return qvr;
        
    }
    public static Vosf_Question_Visibility_Criteria__c createQuestionVisibilityCriteria(Boolean isInsert,Id visibilityRuleId,Id choiceId,string operator,String value) {
        Vosf_Question_Visibility_Criteria__c qvc=new Vosf_Question_Visibility_Criteria__c(Question_Choice__c=choiceId,Question_Visibility_Rule__c=visibilityRuleId,Operator__c=operator,Value__c=value );
        if (isInsert) {
            insert qvc;
        }
        return qvc;
        
    }
    public static Vosf_Question_Choice__c createQuestionChoice(Boolean isInsert,Id questionId,String value,String type) {
        Vosf_Question_Choice__c qc=new Vosf_Question_Choice__c(Question__c=questionId,Value__c=value,Type__c=type);
        if (isInsert) {
            insert qc;
        }
        return qc;
        
    }
    public static Vosf_Survey__c createSurvey(Boolean isInsert,String status,String Name) {
        Vosf_Survey__c survey=new Vosf_Survey__c(Status__c=status,Name=Name);
        if (isInsert) {
            insert survey;
        }
        return survey;
    }

    public static Vosf_Survey_Invitation__c  createSurveyInvitation(Boolean isInsert,Id surveyId,String status) {
        System.debug(UserInfo.getUserId());
        Vosf_Survey_Invitation__c   surveyInvitation=new Vosf_Survey_Invitation__c(Survey__c=surveyId,Status__c=status,Participant__c=UserInfo.getUserId());
        if (isInsert) {
            insert surveyInvitation;
        }
        return surveyInvitation;
    }
    
    public static Vosf_Question_Response__c createQuestionResponse(Boolean isInsert,Id quetionId,Id choiceId,String response,String SinvitationId) {
        Vosf_Question_Response__c qs=new Vosf_Question_Response__c(Response__c=response,Question__c=quetionId,Question_Choice__c=choiceId,Survey_Invitation__c=SinvitationId);
        if (isInsert) {
            insert qs;
        }
        return qs;
    }    
    
    public static List<Vosf_Survey_Question__c> createSurveyQuestion(Id surveyId,List<Id> listOfQuestionId){
        List<Vosf_Survey_Question__c> surveyQuestionList = new List<Vosf_Survey_Question__c>();
        for(String questionId : listOfQuestionId){
            Vosf_Survey_Question__c surveyQuestion = new Vosf_Survey_Question__c(Question__c = questionId, Survey__c = surveyId);
            surveyQuestionList.add(surveyQuestion);
        }
        if(!surveyQuestionList.isEmpty()){
            Database.insert(surveyQuestionList,false);
        }
        return surveyQuestionList;
    }

    public static Vosf_Related_Question__c createRelatedQuestion(Id question,Id relatedQuestion,Id relatedquestioncolumn) {
        Vosf_Related_Question__c rqobj=new Vosf_Related_Question__c(Question__c=question,Related_Question__c=relatedQuestion,Related_Question_Column__c=relatedquestioncolumn);
        return rqobj;
    }
}