objects/Vosf_Survey__c.object
<CustomObject>
    <label>Survey</label>
    <nameField>
        <label>Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Vosf_Survey_Invitation__c.object
<CustomObject>
    <fields>
        <fullName>Due_Date__c</fullName>
        <defaultValue>TODAY() + $Setup.Vosf_Survey_Setting__c.Due_Date_Period__c</defaultValue>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <label>Survey Invitation</label>
    <nameField>
        <displayFormat>SI-{YY}{MM}{00000}</displayFormat>
        <label>Survey Invitation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Invitations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/Vosf_SurveyReminderBatchTest.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 05-10-2023
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
@IsTest
public class Vosf_SurveyReminderBatchTest {
    @TestSetup static void createTestData() {
        VOSF_TestDataFactory.createSurveySetting(true,true);
        Vosf_Survey__c survey = VOSF_TestDataFactory.createSurvey(true,'Draft','Test Survey');
        Id surveyId = survey.Id;
        
    	Vosf_Survey_Invitation__c surveyInvitation = VOSF_TestDataFactory.createSurveyInvitation(false, surveyId, 'Not Started');
        surveyInvitation.Due_Date__c = Date.today();
        insert surveyInvitation;
    }
    
    @IsTest
    static void sendReminderEmailTest() {
        
        Test.startTest();
        String chron = '0 0 23 * * ?';
        Vosf_SurveyReminderBatch srb=new Vosf_SurveyReminderBatch();
       String jobId= system.schedule('Reminder Batch', chron, srb); 
        CronTrigger ct = [Select id , CronExpression from CronTrigger where id = :jobId];
        System.assertEquals(chron,ct.CronExpression); 
        Test.stopTest();
    }
}