objects/Vosf_Survey__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Survey_Period__c</fullName>
        <label>Survey Period</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Week</fullName>
                    <default>true</default>
                    <label>Week</label>
                </value>
                <value>
                    <fullName>Month</fullName>
                </value>
                <value>
                    <fullName>Account Annually</fullName>
                </value>
                <value>
                    <fullName>Season</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Welcome_Page_Content__c</fullName>
        <label>Welcome Page Content</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <label>Survey</label>
    <nameField>
        <label>Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Vosf_Survey_Invitation__c.object
<CustomObject>
    <fields>
        <fullName>Last_Answered_Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Last Answered Question</label>
        <referenceTo>Vosf_Question__c</referenceTo>
        <relationshipLabel>Survey Invitations</relationshipLabel>
        <relationshipName>Survey_Invitations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Participant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Participant</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Survey_Invitations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Survey_Link__c</fullName>
        <label>Survey Link</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Survey</label>
        <referenceTo>Vosf_Survey__c</referenceTo>
        <relationshipLabel>Survey Invitations</relationshipLabel>
        <relationshipName>Survey_Invitations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Survey Invitation</label>
    <nameField>
        <displayFormat>SI-{YY}{MM}{00000}</displayFormat>
        <label>Survey Invitation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Invitations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/Vosf_SurveyInvitationDAO.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 06-01-2023
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public with sharing class Vosf_SurveyInvitationDAO {
	public static List<Vosf_Survey_Invitation__c> getSurveyInvitationByIDs(Set<Id> surveyInvitationIds){
        return [
            SELECT Id, Survey__c, Participant__c, Participant__r.Email,Survey_Link__c, 
                Survey__r.Welcome_Page_Content__c,Participant__r.Name  
            FROM Vosf_Survey_Invitation__c 
            WHERE Id IN:surveyInvitationIds AND Participant__r.Email != null
            ];
    }
    
    public static List<Vosf_Survey_Invitation__c> getSurveyInvitationByID(Id surveyInvitationId){
        return [
            SELECT Id, Survey__r.Welcome_Page_Content__c, Survey__r.Survey_Period__c,Participant__r.Name,Survey_Link__c,
                Last_Answered_Question__c, Status__c 
            FROM Vosf_Survey_Invitation__c 
            WHERE Id =:surveyInvitationId];
    }
    /**
     * @description return all the survey
     * @return  `List<Vosf_Survey__c>`
     */
    public static List<Vosf_Survey__c> getAllSurvey(){
        return [SELECT Id,Name FROM Vosf_Survey__c ];
    }
}