objects/Vosf_Module__c.object
<CustomObject>
    <fields>
        <fullName>Parent_Module__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Module</label>
        <referenceTo>Vosf_Module__c</referenceTo>
        <relationshipLabel>Sub Modules</relationshipLabel>
        <relationshipName>Sub_Module</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Module</label>
    <nameField>
        <label>Module Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Modules</pluralLabel>
    <recordTypes>
        <fullName>Module</fullName>
        <active>true</active>
        <label>Module</label>
    </recordTypes>
    <recordTypes>
        <fullName>Sub_Module</fullName>
        <active>true</active>
        <label>Sub Module</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Vosf_Question__c.object
<CustomObject>
    <fields>
        <fullName>Module__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Module</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Vosf_Module__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Module</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Vosf_Module__c</referenceTo>
        <relationshipLabel>Questions (Module)</relationshipLabel>
        <relationshipName>Questions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Parent_Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Question</label>
        <referenceTo>Vosf_Question__c</referenceTo>
        <relationshipName>Questions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sub_Module__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sub-Module</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Vosf_Module__c.Parent_Module__c</field>
                <operation>equals</operation>
                <valueField>$Source.Module__c</valueField>
            </filterItems>
            <filterItems>
                <field>Vosf_Module__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>Sub_Module</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Vosf_Module__c</referenceTo>
        <relationshipLabel>Questions (Sub-Module)</relationshipLabel>
        <relationshipName>Questions1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Vosf_Survey__c.object
<CustomObject>
    <label>Survey</label>
    <nameField>
        <label>Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Vosf_Survey_Question__c.object
<CustomObject>
    <fields>
        <fullName>Question__c</fullName>
        <label>Question</label>
        <referenceTo>Vosf_Question__c</referenceTo>
        <relationshipName>Vosf_Survey_Questions</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <label>Survey</label>
        <referenceTo>Vosf_Survey__c</referenceTo>
        <relationshipName>Vosf_Survey_Questions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Survey Question</label>
    <nameField>
        <displayFormat>SQ-{0000}</displayFormat>
        <label>Vosf Validation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Vosf_SurveyControllerTest.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 05-12-2023
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
@IsTest
public class Vosf_SurveyControllerTest {
    
	@TestSetup static void createTestData() {
		VOSF_TestDataFactory.createSurvey(true,'Draft','Test Survey');
        Vosf_Module__c module = VOSF_TestDataFactory.createModule(true,'Module',
                                Schema.SObjectType.Vosf_Module__c.getRecordTypeInfosByDeveloperName()
                                .get('Module').getRecordTypeId());
        Vosf_Module__c submodule = VOSF_TestDataFactory.createModule(false,'Sub-Module',
                                Schema.SObjectType.Vosf_Module__c.getRecordTypeInfosByDeveloperName()
                                .get('Sub_Module').getRecordTypeId());
        submodule.Parent_Module__c = module.Id;
        insert submodule;
        Vosf_Question__c parentQuestion = VOSF_TestDataFactory.createQuestion(true,'Text','Parent Question Label');
        Vosf_Question__c question = VOSF_TestDataFactory.createQuestion(false,'Text','Question Label');
        question.Module__c = module.Id;
        question.Sub_Module__c = submodule.Id;
        question.Parent_Question__c = parentQuestion.Id;
        insert question;
	}
    
    @IsTest
    private static void createSurveyQuestionsTest() {
        String questionId = [SELECT Id FROM Vosf_Question__c LIMIT 1]?.Id;
        Test.startTest();
        Vosf_SurveyController.createSurveyQuestions([SELECT Id FROM Vosf_Survey__c LIMIT 1]?.Id,
                                                    new List<String>{questionId});
        Test.stopTest();
        List<Vosf_Survey_Question__c> surveyQuestions = [SELECT Id,Survey__c,Question__c FROM Vosf_Survey_Question__c];
        System.assertEquals(surveyQuestions != null,true,'Expected to not be null');
        System.assertEquals(surveyQuestions.size() > 0 ,true,'Expected list size to be > 0');
    }
    
    @IsTest
    private static void insertSurveyQuestionsTest() {
        String questionId = [SELECT Id FROM Vosf_Question__c LIMIT 1]?.Id;
        Test.startTest();
        Vosf_SurveyController.insertSurveyQuestions([SELECT Id FROM Vosf_Survey__c LIMIT 1]?.Id,
                                                    new List<String>{questionId});
        Test.stopTest();
        List<Vosf_Survey_Question__c> surveyQuestions = [SELECT Id,Survey__c,Question__c FROM Vosf_Survey_Question__c];
        System.assertEquals(surveyQuestions != null,true,'Expected to not be null');
        System.assertEquals(surveyQuestions.size() > 0 ,true,'Expected list size to be > 0');
    }
    
    @IsTest
    private static void getQuestionsForModulesTest() {
        List<String> moduleIds = new List<String>();
        for(Vosf_Module__c module : [SELECT Id FROM Vosf_Module__c]){
            moduleIds.add(module.Id);
        }
        Test.startTest();
        List<Vosf_SurveyController.QuestionWrapper> questionsWrapper = Vosf_SurveyController.getQuestionsForModules(moduleIds);
        Test.stopTest();
        System.assertEquals(questionsWrapper != null,true,'Expected to not be null');
        System.assertEquals(questionsWrapper.size() > 0 ,true,'Expected list size to be > 0');
    }
    
    @IsTest
    private static void hasChildQuestionsTest() {
        String questionId = [SELECT Id FROM Vosf_Question__c WHERE Parent_Question__c != null LIMIT 1]?.Id;
        Test.startTest();
        Boolean hasChild = Vosf_SurveyController.hasChildQuestions(new List<String>{questionId});
        Test.stopTest();
        System.assertEquals(hasChild,true,'Expected to be true');
    }
}